/*
 * Barajas.cpp
 *
 *  Created on: 04/2022
 *
 *
 *  Copyright 2022 Alberto Hermida
 *
 *  This file is part of ATCSimROS_2.
 *
 *  ATCSimROS_2 is free software based on the ATCsim project , created for a
 *	final project of the Aerospace Engineering at URJC (Madrid).
 *	Author: Alberto Hermida Vazquez (ahermidavazquez@gmail.com)
 *	Tutor: Jose Miguel Guerrero
 *  Author of ATCsim project: Francisco Martin
 * 
 *  ATCSim is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *
 */

#include <visualization_msgs/Marker.h>
#include <visualization_msgs/MarkerArray.h>

#include "tf2/transform_datatypes.h"
#include "tf2/LinearMath/Transform.h"
#include "geometry_msgs/TransformStamped.h"
#include "tf2_geometry_msgs/tf2_geometry_msgs.h"
#include "tf2/convert.h"
#include "tf2_ros/transform_broadcaster.h"
#include "tf2/LinearMath/Quaternion.h"

#include "Barajas.h"

void
Airport_shape::generate_airport_terminal()
{
  visualization_msgs::MarkerArray airport_terminal_array;

  visualization_msgs::Marker setpoint1;
  setpoint1.header.frame_id = "world";
  setpoint1.header.stamp = ros::Time::now();
  setpoint1.ns = "T4";
  setpoint1.id = 20;
  setpoint1.action = visualization_msgs::Marker::ADD;
  setpoint1.type = visualization_msgs::Marker::CUBE;
  setpoint1.pose.position.x = 200;
  setpoint1.pose.position.y = -3230;
  setpoint1.pose.position.z = 0;
  setpoint1.pose.orientation.w = 1.0;
  setpoint1.pose.orientation.x = 60.0;
  setpoint1.pose.orientation.y = 45.0;
  setpoint1.scale.x = 600;
  setpoint1.scale.y = 100;
  setpoint1.scale.z = 200;
  setpoint1.color.r = 0.0f;
  setpoint1.color.g = 0.0f;
  setpoint1.color.b = 0.0f;
  setpoint1.color.a = 1.0;
  airport_terminal_array.markers.push_back(setpoint1);

  visualization_msgs::Marker setpoint2;
  setpoint2.header.frame_id = "world";
  setpoint2.header.stamp = ros::Time::now();
  setpoint2.ns = "T4S";
  setpoint2.id = 21;
  setpoint2.action = visualization_msgs::Marker::ADD;
  setpoint2.type = visualization_msgs::Marker::CUBE;
  setpoint2.pose.position.x = 2280;
  setpoint2.pose.position.y = -3320;
  setpoint2.pose.orientation.w = 1.0;
  setpoint2.pose.orientation.x = 60.0;
  setpoint2.pose.orientation.y = 45.0;
  setpoint2.scale.x = 600;
  setpoint2.scale.y = 100;
  setpoint2.scale.z = 200;
  setpoint2.color.r = 0.0f;
  setpoint2.color.g = 0.0f;
  setpoint2.color.b = 0.0f;
  setpoint2.color.a = 1.0;
  airport_terminal_array.markers.push_back(setpoint2);

  visualization_msgs::Marker setpoint3;
  setpoint3.header.frame_id = "world";
  setpoint3.header.stamp = ros::Time::now();
  setpoint3.ns = "T123";
  setpoint3.id = 22;
  setpoint3.action = visualization_msgs::Marker::ADD;
  setpoint3.type = visualization_msgs::Marker::CUBE;
  setpoint3.pose.position.x = 1550;
  setpoint3.pose.position.y = -6350;
  setpoint3.pose.orientation.w = 1.0;
  setpoint3.pose.orientation.x = 60.0;
  setpoint3.pose.orientation.y = 45.0;
  setpoint3.scale.x = 900;
  setpoint3.scale.y = 100;
  setpoint3.scale.z = 200;
  setpoint3.color.r = 0.0f;
  setpoint3.color.g = 0.0f;
  setpoint3.color.b = 0.0f;
  setpoint3.color.a = 1.0;
  airport_terminal_array.markers.push_back(setpoint3);

  geometry_msgs::Point p1, p2, p3, p4, p5, p6, p7, p8, p9, p10;

  visualization_msgs::Marker runaway3;
  runaway3.header.frame_id = "world";
  runaway3.header.stamp = ros::Time::now();
  runaway3.ns = "32L/14R";
  runaway3.id = 23;
  runaway3.action = visualization_msgs::Marker::ADD;
  runaway3.type = visualization_msgs::Marker::LINE_STRIP;
  runaway3.scale.x = 50;
  runaway3.color.r = 0.0;
  runaway3.color.g = 0.0;
  runaway3.color.b = 0.0;
  runaway3.color.a = 0.3;
  runaway3.pose.orientation.w = 1.0;
  p1.x=2700;
  p1.y=-7650;
  p1.z=0;
  p2.x=1450;
  p2.y=-4250;
  p2.z=0;
  runaway3.points.push_back(p1);
  runaway3.points.push_back(p2);
  airport_terminal_array.markers.push_back(runaway3);

  visualization_msgs::Marker runaway4;
  runaway4.header.frame_id = "world";
  runaway4.header.stamp = ros::Time::now();
  runaway4.ns = "32R/14L";
  runaway4.id = 24;
  runaway4.action = visualization_msgs::Marker::ADD;
  runaway4.type = visualization_msgs::Marker::LINE_STRIP;
  runaway4.scale.x = 50;
  runaway4.color.r = 0.0;
  runaway4.color.g = 0.0;
  runaway4.color.b = 0.0;
  runaway4.color.a = 0.3;
  runaway4.pose.orientation.w = 1.0;
  p1.x=4420;
  p1.y=-6780;
  p1.z=0;
  p2.x=3280;
  p2.y=-3600;
  p2.z=0;
  runaway4.points.push_back(p1);
  runaway4.points.push_back(p2);
  airport_terminal_array.markers.push_back(runaway4);

  visualization_msgs::Marker runaway1;
  runaway1.header.frame_id = "world";
  runaway1.header.stamp = ros::Time::now();
  runaway1.ns = "18R/36L";
  runaway1.id = 24;
  runaway1.action = visualization_msgs::Marker::ADD;
  runaway1.type = visualization_msgs::Marker::LINE_STRIP;
  runaway1.scale.x = 50;
  runaway1.color.r = 0.0;
  runaway1.color.g = 0.0;
  runaway1.color.b = 0.0;
  runaway1.color.a = 0.3;
  runaway1.pose.orientation.w = 1.0;
  p1.x=1800;
  p1.y=-2400;
  p1.z=0;
  p2.x=2850;
  p2.y=1000;
  p2.z=0;
  runaway1.points.push_back(p1);
  runaway1.points.push_back(p2);
  airport_terminal_array.markers.push_back(runaway1);

  visualization_msgs::Marker runaway2;
  runaway2.header.frame_id = "world";
  runaway2.header.stamp = ros::Time::now();
  runaway2.ns = "18L/36R";
  runaway2.id = 24;
  runaway2.action = visualization_msgs::Marker::ADD;
  runaway2.type = visualization_msgs::Marker::LINE_STRIP;
  runaway2.scale.x = 50;
  runaway2.color.r = 0.0;
  runaway2.color.g = 0.0;
  runaway2.color.b = 0.0;
  runaway2.color.a = 0.3;
  runaway2.pose.orientation.w = 1.0;
  p1.x=3150;
  p1.y=-2425;
  p1.z=0;
  p2.x=4280;
  p2.y=1200;
  p2.z=0;
  runaway2.points.push_back(p1);
  runaway2.points.push_back(p2);
  airport_terminal_array.markers.push_back(runaway2);


  visualization_msgs::Marker route1;
  route1.header.frame_id = "world";
  route1.header.stamp = ros::Time::now();
  route1.ns = "ROUTE 1";
  route1.id = 24;
  route1.action = visualization_msgs::Marker::ADD;
  route1.type = visualization_msgs::Marker::LINE_STRIP;
  route1.scale.x = 25;
  route1.color.r = 0.0;
  route1.color.g = 0.0;
  route1.color.b = 0.0;
  route1.color.a = 0.3;
  route1.pose.orientation.w = 1.0;
  p1.x=1720;
  p1.y=-5000;
  p1.z=0;
  p2.x=1450;
  p2.y=-4800;
  p2.z=0;
  p3.x=1520;
  p3.y=-5000;
  p3.z=0;
  p4.x=1750;
  p4.y=-5600;
  p4.z=0;
  p5.x=1660;
  p5.y=-5900;
  p5.z=0;
  route1.points.push_back(p1);
  route1.points.push_back(p2);
  route1.points.push_back(p3);
  route1.points.push_back(p4);
  route1.points.push_back(p5);
  airport_terminal_array.markers.push_back(route1);

  visualization_msgs::Marker route2;
  route2.header.frame_id = "world";
  route2.header.stamp = ros::Time::now();
  route2.ns = "ROUTE 2";
  route2.id = 24;
  route2.action = visualization_msgs::Marker::ADD;
  route2.type = visualization_msgs::Marker::LINE_STRIP;
  route2.scale.x = 25;
  route2.color.r = 0.0;
  route2.color.g = 0.0;
  route2.color.b = 0.0;
  route2.color.a = 0.3;
  route2.pose.orientation.w = 1.0;
  p1.x=1450;
  p1.y=-4250;
  p1.z=0;
  p2.x=1170;
  p2.y=-4050;
  p2.z=0;
  p3.x=1450;
  p3.y=-4800;
  p3.z=0;
  route2.points.push_back(p1);
  route2.points.push_back(p2);
  route2.points.push_back(p3);
  airport_terminal_array.markers.push_back(route2);

  visualization_msgs::Marker route3;
  route3.header.frame_id = "world";
  route3.header.stamp = ros::Time::now();
  route3.ns = "ROUTE 3";
  route3.id = 24;
  route3.action = visualization_msgs::Marker::ADD;
  route3.type = visualization_msgs::Marker::LINE_STRIP;
  route3.scale.x = 25;
  route3.color.r = 0.0;
  route3.color.g = 0.0;
  route3.color.b = 0.0;
  route3.color.a = 0.3;
  route3.pose.orientation.w = 1.0;
  p1.x=1520;
  p1.y=-5000;
  p1.z=0;
  p2.x=1430;
  p2.y=-5030;
  p2.z=0;
  p3.x=880;
  p3.y=-3450;
  p3.z=0;
  p4.x=960;
  p4.y=-3200;
  p4.z=0;
  p5.x=2120;
  p5.y=-3580;
  p5.z=0;
  route3.points.push_back(p1);
  route3.points.push_back(p2);
  route3.points.push_back(p3);
  route3.points.push_back(p4);
  route3.points.push_back(p5);
  airport_terminal_array.markers.push_back(route3);

  visualization_msgs::Marker route4;
  route4.header.frame_id = "world";
  route4.header.stamp = ros::Time::now();
  route4.ns = "ROUTE 4";
  route4.id = 24;
  route4.action = visualization_msgs::Marker::ADD;
  route4.type = visualization_msgs::Marker::LINE_STRIP;
  route4.scale.x = 25;
  route4.color.r = 0.0;
  route4.color.g = 0.0;
  route4.color.b = 0.0;
  route4.color.a = 0.3;
  route4.pose.orientation.w = 1.0;
  p1.x=880;
  p1.y=-3450;
  p1.z=0;
  p2.x=200;
  p2.y=-3230;
  p2.z=0;
  route4.points.push_back(p1);
  route4.points.push_back(p2);
  airport_terminal_array.markers.push_back(route4);

  visualization_msgs::Marker route5;
  route5.header.frame_id = "world";
  route5.header.stamp = ros::Time::now();
  route5.ns = "ROUTE 5";
  route5.id = 24;
  route5.action = visualization_msgs::Marker::ADD;
  route5.type = visualization_msgs::Marker::LINE_STRIP;
  route5.scale.x = 25;
  route5.color.r = 0.0;
  route5.color.g = 0.0;
  route5.color.b = 0.0;
  route5.color.a = 0.3;
  route5.pose.orientation.w = 1.0;
  p1.x=3280;
  p1.y=-3600;
  p1.z=0;
  p2.x=2950;
  p2.y=-3350;
  p2.z=0;
  p3.x=2900;
  p3.y=-3200;
  p3.z=0;
  p4.x=2510;
  p4.y=-3075;
  p4.z=0;
  p5.x=2310;
  p5.y=-3750;
  p5.z=0;
  p6.x=2080;
  p6.y=-3680;
  p6.z=0;
  p7.x=2120;
  p7.y=-3580;
  p7.z=0;
  p8.x=2200;
  p8.y=-3300;
  p8.z=0;
  route5.points.push_back(p1);
  route5.points.push_back(p2);
  route5.points.push_back(p3);
  route5.points.push_back(p4);
  route5.points.push_back(p5);
  route5.points.push_back(p6);
  route5.points.push_back(p7);
  route5.points.push_back(p8);
  airport_terminal_array.markers.push_back(route5);

  visualization_msgs::Marker route6;
  route6.header.frame_id = "world";
  route6.header.stamp = ros::Time::now();
  route6.ns = "ROUTE 6";
  route6.id = 24;
  route6.action = visualization_msgs::Marker::ADD;
  route6.type = visualization_msgs::Marker::LINE_STRIP;
  route6.scale.x = 25;
  route6.color.r = 0.0;
  route6.color.g = 0.0;
  route6.color.b = 0.0;
  route6.color.a = 0.3;
  route6.pose.orientation.w = 1.0;
  p1.x=3450;
  p1.y=-4080;
  p1.z=0;
  p2.x=3150;
  p2.y=-3890;
  p2.z=0;
  p3.x=3050;
  p3.y=-3600;
  p3.z=0;
  p4.x=2950;
  p4.y=-3350;
  p4.z=0;
  route6.points.push_back(p1);
  route6.points.push_back(p2);
  route6.points.push_back(p3);
  route6.points.push_back(p4);
  airport_terminal_array.markers.push_back(route6);

  visualization_msgs::Marker route7;
  route7.header.frame_id = "world";
  route7.header.stamp = ros::Time::now();
  route7.ns = "ROUTE 7";
  route7.id = 24;
  route7.action = visualization_msgs::Marker::ADD;
  route7.type = visualization_msgs::Marker::LINE_STRIP;
  route7.scale.x = 25;
  route7.color.r = 0.0;
  route7.color.g = 0.0;
  route7.color.b = 0.0;
  route7.color.a = 0.3;
  route7.pose.orientation.w = 1.0;
  p1.x=2080;
  p1.y=-3680;
  p1.z=0;
  p2.x=1000;
  p2.y=-3320;
  p2.z=0;
  p3.x=950;
  p3.y=-3480;
  p3.z=0;
  p4.x=880;
  p4.y=-3450;
  p4.z=0;
  route7.points.push_back(p1);
  route7.points.push_back(p2);
  route7.points.push_back(p3);
  route7.points.push_back(p4);
  airport_terminal_array.markers.push_back(route7);

  visualization_msgs::Marker route8;
  route8.header.frame_id = "world";
  route8.header.stamp = ros::Time::now();
  route8.ns = "ROUTE 8";
  route8.id = 24;
  route8.action = visualization_msgs::Marker::ADD;
  route8.type = visualization_msgs::Marker::LINE_STRIP;
  route8.scale.x = 25;
  route8.color.r = 0.0;
  route8.color.g = 0.0;
  route8.color.b = 0.0;
  route8.color.a = 0.3;
  route8.pose.orientation.w = 1.0;
  p1.x=950;
  p1.y=-3480;
  p1.z=0;
  p2.x=1170;
  p2.y=-4050;
  p2.z=0;
  route8.points.push_back(p1);
  route8.points.push_back(p2);
  airport_terminal_array.markers.push_back(route8);

  visualization_msgs::Marker route9;
  route9.header.frame_id = "world";
  route9.header.stamp = ros::Time::now();
  route9.ns = "ROUTE 9";
  route9.id = 24;
  route9.action = visualization_msgs::Marker::ADD;
  route9.type = visualization_msgs::Marker::LINE_STRIP;
  route9.scale.x = 25;
  route9.color.r = 0.0;
  route9.color.g = 0.0;
  route9.color.b = 0.0;
  route9.color.a = 0.3;
  route9.pose.orientation.w = 1.0;
  p1.x=2200;
  p1.y=-3300;
  p1.z=0;
  p2.x=2230;
  p2.y=-3210;
  p2.z=0;
  p3.x=1620;
  p3.y=-3020;
  p3.z=0;
  p4.x=1650;
  p4.y=-2900;
  p4.z=0;
  p5.x=1800;
  p5.y=-2400;
  p5.z=0;
  route9.points.push_back(p1);
  route9.points.push_back(p2);
  route9.points.push_back(p3);
  route9.points.push_back(p4);
  route9.points.push_back(p5);
  airport_terminal_array.markers.push_back(route9);

  visualization_msgs::Marker route10;
  route10.header.frame_id = "world";
  route10.header.stamp = ros::Time::now();
  route10.ns = "ROUTE 10";
  route10.id = 24;
  route10.action = visualization_msgs::Marker::ADD;
  route10.type = visualization_msgs::Marker::LINE_STRIP;
  route10.scale.x = 25;
  route10.color.r = 0.0;
  route10.color.g = 0.0;
  route10.color.b = 0.0;
  route10.color.a = 0.3;
  route10.pose.orientation.w = 1.0;
  p1.x=200;
  p1.y=-3230;
  p1.z=0;
  p2.x=420;
  p2.y=-2520;
  p2.z=0;
  p3.x=1650;
  p3.y=-2900;
  p3.z=0;
  route10.points.push_back(p1);
  route10.points.push_back(p2);
  route10.points.push_back(p3);
  airport_terminal_array.markers.push_back(route10);

  visualization_msgs::Marker route11;
  route11.header.frame_id = "world";
  route11.header.stamp = ros::Time::now();
  route11.ns = "ROUTE 11";
  route11.id = 24;
  route11.action = visualization_msgs::Marker::ADD;
  route11.type = visualization_msgs::Marker::LINE_STRIP;
  route11.scale.x = 25;
  route11.color.r = 0.0;
  route11.color.g = 0.0;
  route11.color.b = 0.0;
  route11.color.a = 0.3;
  route11.pose.orientation.w = 1.0;
  p1.x=1660;
  p1.y=-5900;
  p1.z=0;
  p2.x=1500;
  p2.y=-5850;
  p2.z=0;
  p3.x=1600;
  p3.y=-5500;
  p3.z=0;
  p4.x=1430;
  p4.y=-5030;
  p4.z=0;
  route11.points.push_back(p1);
  route11.points.push_back(p2);
  route11.points.push_back(p3);
  route11.points.push_back(p4);
  airport_terminal_array.markers.push_back(route11);

  visualization_msgs::Marker route12;
  route12.header.frame_id = "world";
  route12.header.stamp = ros::Time::now();
  route12.ns = "ROUTE 12";
  route12.id = 24;
  route12.action = visualization_msgs::Marker::ADD;
  route12.type = visualization_msgs::Marker::LINE_STRIP;
  route12.scale.x = 25;
  route12.color.r = 0.0;
  route12.color.g = 0.0;
  route12.color.b = 0.0;
  route12.color.a = 0.3;
  route12.pose.orientation.w = 1.0;
  p1.x=1930;
  p1.y=-3110;
  p1.z=0;
  p2.x=2230;
  p2.y=-2130;
  p2.z=0;
  p3.x=2910;
  p3.y=-2350;
  p3.z=0;
  route12.points.push_back(p1);
  route12.points.push_back(p2);
  route12.points.push_back(p3);
  airport_terminal_array.markers.push_back(route12);

  visualization_msgs::Marker route13;
  route13.header.frame_id = "world";
  route13.header.stamp = ros::Time::now();
  route13.ns = "ROUTE 13";
  route13.id = 24;
  route13.action = visualization_msgs::Marker::ADD;
  route13.type = visualization_msgs::Marker::LINE_STRIP;
  route13.scale.x = 25;
  route13.color.r = 0.0;
  route13.color.g = 0.0;
  route13.color.b = 0.0;
  route13.color.a = 0.3;
  route13.pose.orientation.w = 1.0;
  p1.x=2120;
  p1.y=-3580;
  p1.z=0;
  p2.x=2500;
  p2.y=-3700;
  p2.z=0;
  p3.x=2910;
  p3.y=-2350;
  p3.z=0;
  p4.x=3150;
  p4.y=-2425;
  p4.z=0;
  route13.points.push_back(p1);
  route13.points.push_back(p2);
  route13.points.push_back(p3);
  route13.points.push_back(p4);
  airport_terminal_array.markers.push_back(route13);

  visualization_msgs::Marker route14;
  route14.header.frame_id = "world";
  route14.header.stamp = ros::Time::now();
  route14.ns = "ROUTE 14";
  route14.id = 24;
  route14.action = visualization_msgs::Marker::ADD;
  route14.type = visualization_msgs::Marker::LINE_STRIP;
  route14.scale.x = 25;
  route14.color.r = 0.0;
  route14.color.g = 0.0;
  route14.color.b = 0.0;
  route14.color.a = 0.3;
  route14.pose.orientation.w = 1.0;
  p1.x=280;
  p1.y=-2980;
  p1.z=0;
  p2.x=960;
  p2.y=-3200;
  p2.z=0;
  route14.points.push_back(p1);
  route14.points.push_back(p2);
  airport_terminal_array.markers.push_back(route14);


  visualization_msgs::Marker collision_point_1;
  collision_point_1.header.frame_id = "world";
  collision_point_1.header.stamp = ros::Time::now();
  collision_point_1.ns = "COLLISION POINT 1";
  collision_point_1.id = 25;
  collision_point_1.action = visualization_msgs::Marker::ADD;
  collision_point_1.type = visualization_msgs::Marker::SPHERE;
  collision_point_1.pose.position.x = 1170;
  collision_point_1.pose.position.y = -4050;
  collision_point_1.pose.position.z = 0;
  collision_point_1.scale.x = 100;
  collision_point_1.scale.y = 100;
  collision_point_1.scale.z = 100;
  collision_point_1.color.b = 1.0f;
  collision_point_1.color.a = 1.0;
  collision_point_1.pose.orientation.w = 1.0;
  airport_terminal_array.markers.push_back(collision_point_1);

  visualization_msgs::Marker collision_point_2;
  collision_point_2.header.frame_id = "world";
  collision_point_2.header.stamp = ros::Time::now();
  collision_point_2.ns = "COLLISION POINT 2";
  collision_point_2.id = 26;
  collision_point_2.action = visualization_msgs::Marker::ADD;
  collision_point_2.type = visualization_msgs::Marker::SPHERE;
  collision_point_2.pose.position.x = 1450;
  collision_point_2.pose.position.y = -4800;
  collision_point_2.pose.position.z = 0;
  collision_point_2.scale.x = 100;
  collision_point_2.scale.y = 100;
  collision_point_2.scale.z = 100;
  collision_point_2.color.b = 1.0f;
  collision_point_2.color.a = 1.0;
  collision_point_2.pose.orientation.w = 1.0;
  airport_terminal_array.markers.push_back(collision_point_2);

  visualization_msgs::Marker collision_point_3;
  collision_point_3.header.frame_id = "world";
  collision_point_3.header.stamp = ros::Time::now();
  collision_point_3.ns = "COLLISION POINT 3";
  collision_point_3.id = 27;
  collision_point_3.action = visualization_msgs::Marker::ADD;
  collision_point_3.type = visualization_msgs::Marker::SPHERE;
  collision_point_3.pose.position.x = 2340;
  collision_point_3.pose.position.y = -3650;
  collision_point_3.pose.position.z = 0;
  collision_point_3.scale.x = 100;
  collision_point_3.scale.y = 100;
  collision_point_3.scale.z = 100;
  collision_point_3.color.b = 1.0f;
  collision_point_3.color.a = 1.0;
  collision_point_3.pose.orientation.w = 1.0;
  airport_terminal_array.markers.push_back(collision_point_3);

  visualization_msgs::Marker collision_point_4;
  collision_point_4.header.frame_id = "world";
  collision_point_4.header.stamp = ros::Time::now();
  collision_point_4.ns = "COLLISION POINT 4";
  collision_point_4.id = 28;
  collision_point_4.action = visualization_msgs::Marker::ADD;
  collision_point_4.type = visualization_msgs::Marker::SPHERE;
  collision_point_4.pose.position.x = 1430;
  collision_point_4.pose.position.y = -5030;
  collision_point_4.pose.position.z = 0;
  collision_point_4.scale.x = 100;
  collision_point_4.scale.y = 100;
  collision_point_4.scale.z = 100;
  collision_point_4.color.b = 1.0f;
  collision_point_4.color.a = 1.0;
  collision_point_4.pose.orientation.w = 1.0;
  airport_terminal_array.markers.push_back(collision_point_4);

  visualization_msgs::Marker collision_point_5;
  collision_point_5.header.frame_id = "world";
  collision_point_5.header.stamp = ros::Time::now();
  collision_point_5.ns = "COLLISION POINT 5";
  collision_point_5.id = 28;
  collision_point_5.action = visualization_msgs::Marker::ADD;
  collision_point_5.type = visualization_msgs::Marker::SPHERE;
  collision_point_5.pose.position.x = 2120;
  collision_point_5.pose.position.y = -3580;
  collision_point_5.pose.position.z = 0;
  collision_point_5.scale.x = 100;
  collision_point_5.scale.y = 100;
  collision_point_5.scale.z = 100;
  collision_point_5.color.b = 1.0f;
  collision_point_5.color.a = 1.0;
  collision_point_5.pose.orientation.w = 1.0;
  airport_terminal_array.markers.push_back(collision_point_5);

  visualization_msgs::Marker collision_point_6;
  collision_point_6.header.frame_id = "world";
  collision_point_6.header.stamp = ros::Time::now();
  collision_point_6.ns = "COLLISION POINT 6";
  collision_point_6.id = 30;
  collision_point_6.action = visualization_msgs::Marker::ADD;
  collision_point_6.type = visualization_msgs::Marker::SPHERE;
  collision_point_6.pose.position.x = 960;
  collision_point_6.pose.position.y = -3200;
  collision_point_6.pose.position.z = 0;
  collision_point_6.scale.x = 100;
  collision_point_6.scale.y = 100;
  collision_point_6.scale.z = 100;
  collision_point_6.color.b = 1.0f;
  collision_point_6.color.a = 1.0;
  collision_point_6.pose.orientation.w = 1.0;
  airport_terminal_array.markers.push_back(collision_point_6);

  visualization_msgs::Marker collision_point_7;
  collision_point_7.header.frame_id = "world";
  collision_point_7.header.stamp = ros::Time::now();
  collision_point_7.ns = "COLLISION POINT 7";
  collision_point_7.id = 31;
  collision_point_7.action = visualization_msgs::Marker::ADD;
  collision_point_7.type = visualization_msgs::Marker::SPHERE;
  collision_point_7.pose.position.x = 1650;
  collision_point_7.pose.position.y = -2900;
  collision_point_7.pose.position.z = 0;
  collision_point_7.scale.x = 100;
  collision_point_7.scale.y = 100;
  collision_point_7.scale.z = 100;
  collision_point_7.color.b = 1.0f;
  collision_point_7.color.a = 1.0;
  collision_point_7.pose.orientation.w = 1.0;
  airport_terminal_array.markers.push_back(collision_point_7);

  visualization_msgs::Marker collision_point_8;
  collision_point_8.header.frame_id = "world";
  collision_point_8.header.stamp = ros::Time::now();
  collision_point_8.ns = "COLLISION POINT 8";
  collision_point_8.id = 31;
  collision_point_8.action = visualization_msgs::Marker::ADD;
  collision_point_8.type = visualization_msgs::Marker::SPHERE;
  collision_point_8.pose.position.x = 2670;
  collision_point_8.pose.position.y = -3120;
  collision_point_8.pose.position.z = 0;
  collision_point_8.scale.x = 100;
  collision_point_8.scale.y = 100;
  collision_point_8.scale.z = 100;
  collision_point_8.color.b = 1.0f;
  collision_point_8.color.a = 1.0;
  collision_point_8.pose.orientation.w = 1.0;
  airport_terminal_array.markers.push_back(collision_point_8);

  visualization_msgs::Marker collision_point_9;
  collision_point_9.header.frame_id = "world";
  collision_point_9.header.stamp = ros::Time::now();
  collision_point_9.ns = "COLLISION POINT 9";
  collision_point_9.id = 31;
  collision_point_9.action = visualization_msgs::Marker::ADD;
  collision_point_9.type = visualization_msgs::Marker::SPHERE;
  collision_point_9.pose.position.x = 2910;
  collision_point_9.pose.position.y = -2350;
  collision_point_9.pose.position.z = 0;
  collision_point_9.scale.x = 100;
  collision_point_9.scale.y = 100;
  collision_point_9.scale.z = 100;
  collision_point_9.color.b = 1.0f;
  collision_point_9.color.a = 1.0;
  collision_point_9.pose.orientation.w = 1.0;
  airport_terminal_array.markers.push_back(collision_point_9);

  visualization_msgs::Marker collision_point_10;
  collision_point_10.header.frame_id = "world";
  collision_point_10.header.stamp = ros::Time::now();
  collision_point_10.ns = "COLLISION POINT 10";
  collision_point_10.id = 31;
  collision_point_10.action = visualization_msgs::Marker::ADD;
  collision_point_10.type = visualization_msgs::Marker::SPHERE;
  collision_point_10.pose.position.x = 880;
  collision_point_10.pose.position.y = -3450;
  collision_point_10.pose.position.z = 0;
  collision_point_10.scale.x = 100;
  collision_point_10.scale.y = 100;
  collision_point_10.scale.z = 100;
  collision_point_10.color.b = 1.0f;
  collision_point_10.color.a = 1.0;
  collision_point_10.pose.orientation.w = 1.0;
  airport_terminal_array.markers.push_back(collision_point_10);
  
  airport_terminal_pub.publish(airport_terminal_array);

}

