uint32 code 
string id
string type
string airline
uint32 capacity
uint32 occupation
uint32 terminal
uint32 a_runaway
uint32 d_runaway
uint32 highspeed
float64 posx
float64 posy
float64 posz
float64 speed
float64 bearing
float64 inclination
Waypoint[] wps
float64 speed_req
float64 generation_time

---

bool achieved
string expl
